### ISSUE TITLE
Unknown protocol ssh

### ISSUE THREAD

**Issue by Jonar** [Cosium/vet#24]
Fresh install of vet on Ubuntu. Using ssh as protocol for communicating with gerrit, but get the following error on most commands: 

vet status --verbose --stacktrace
16:41:01 INFO com.cosium.vet.App - Stacktrace printing enabled
16:41:01 INFO com.cosium.vet.App - Verbose mode enabled
16:41:01 DEBUG com.cosium.vet.command.CompositeCommandArgParser - Parsing arguments [status]
16:41:01 DEBUG com.cosium.vet.command.CompositeCommandArgParser - Parsing command using com.cosium.vet.command.status.StatusCommandArgParser@39aeed2f
16:41:01 DEBUG com.cosium.vet.runtime.BasicCommandRunner - Executing 'git config remote.origin.pushurl'
16:41:02 DEBUG com.cosium.vet.git.BasicGitClient - No value found for 'remote.origin.pushurl'. Falling back on 'remote.origin.url'
16:41:02 DEBUG com.cosium.vet.runtime.BasicCommandRunner - Executing 'git config remote.origin.url'
16:41:02 DEBUG com.cosium.vet.runtime.BasicCommandRunner - ssh://user@gerrit.domain.com:29418/path/to.project

16:41:02 ERROR com.cosium.vet.App - java.net.MalformedURLException: unknown protocol: ssh
java.lang.IllegalArgumentException: java.net.MalformedURLException: unknown protocol: ssh
        at com.cosium.vet/com.cosium.vet.git.RemoteUrl.toURL(Unknown Source)
        at java.base/java.util.Optional.map(Unknown Source)
        at com.cosium.vet/com.cosium.vet.gerrit.DefaultChangeRepositoryFactory.build(Unknown Source)
        at com.cosium.vet/com.cosium.vet.command.status.StatusCommand$Factory.build(Unknown Source)
        at com.cosium.vet/com.cosium.vet.command.status.StatusCommandArgParser.parse(Unknown Source)
        at com.cosium.vet/com.cosium.vet.command.CompositeCommandArgParser.parse(Unknown Source)
        at com.cosium.vet/com.cosium.vet.Vet.run(Unknown Source)
        at com.cosium.vet/com.cosium.vet.App.main(Unknown Source)
Caused by: java.net.MalformedURLException: unknown protocol: ssh
        at java.base/java.net.URL.<init>(Unknown Source)
        at java.base/java.net.URL.<init>(Unknown Source)
        at java.base/java.net.URL.<init>(Unknown Source)
        ... 8 more

**Comment by reda-alaoui** [comment]
Fixed by https://github.com/Cosium/vet/commit/87fb5ba9fa7c33dd82c382ccf8a8759e2c91d5bf
